# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: author/최연재
    weight: 10

  - name: activities
    url: recent
    weight: 20
  - parent: activities
    name: awards & certifications
    url: awards
    weight: 20
  - parent: activities
    name: now 
    url: now 
    weight: 20
  

  - name: 프로젝트
    url: project
    weight: 30
  - parent: 프로젝트
    name: 쿠키런 프로젝트
    url: cookierun
    weight: 30
  - parent: 프로젝트
    name: 넷플릭스 클론
    url: netflix
    weight: 30
  - parent: 프로젝트
    name: 학생 관리 시스템
    url: studenmanagement
    weight: 30

  - name: personal
    url: event
    weight: 40
  - parent: personal
    name: 교환학생
    url: exchange
    weight: 40
  - parent: personal
    name: sns
    url: sns
    weight: 40

  - name: 공지
    url: notice
    weight: 50
    
  - name: 연락처
    url: contact
    weight: 60
