# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: tour
    weight: 10

  - name: 이력서
    url: post
    weight: 20

  - name: 프로젝트
    url: people
    weight: 30

  - name: personal
    url: event
    weight: 40
  - parent: personal
    name: experience
    url: event
    weight: 40
  - parent: personal
    name: sns
    url: event
    weight: 40

  - name: 공지
    url: publication
    weight: 50
    
  - name: 연락처
    url: contact
    weight: 60
